import { writeFile } from 'node:fs/promises';
import { relative, dirname, join } from 'node:path';

/**
 * Generate the content of obligations.dfy from gap results.
 *
 * @param {object[]} gapResults - items with status 'gap' from prove step
 * @param {string} domainDfyPath - absolute path to domain .dfy file
 * @param {string} domainModule - Dafny module name
 * @param {string} outputDir - where obligations.dfy will be written
 * @returns {string} Dafny source content
 */
export function generateObligations(gapResults, domainDfyPath, domainModule, outputDir) {
  if (gapResults.length === 0) return null;

  const includePath = relative(outputDir, domainDfyPath);
  const lines = [];

  lines.push(`// Generated by claimcheck — obligations to be discharged`);
  lines.push(`// ${gapResults.length} requirement(s) could not be automatically verified`);
  lines.push(`// Prove these lemmas or refine the requirements`);
  lines.push(``);
  lines.push(`include "${includePath}"`);
  lines.push(``);
  lines.push(`module Obligations {`);
  lines.push(`  import D = ${domainModule}`);
  lines.push(``);

  for (const gap of gapResults) {
    lines.push(`  // Requirement: "${gap.requirement}"`);
    lines.push(`  // Status: unproven after ${gap.attempts} attempt(s)`);
    lines.push(`  // Reasoning: ${gap.reasoning}`);
    if (gap.error) {
      const shortError = gap.error.split('\n').slice(0, 3).join('\n  //   ');
      lines.push(`  // Last error:`);
      lines.push(`  //   ${shortError}`);
    }
    lines.push(`  //`);
    lines.push(`  // Best attempt:`);
    for (const codeLine of gap.dafnyCode.split('\n')) {
      lines.push(`  // ${codeLine}`);
    }
    lines.push(``);
    lines.push(`  ${gap.dafnyCode}`);
    lines.push(``);
  }

  lines.push(`}`);

  return lines.join('\n');
}

/**
 * Write obligations.dfy to disk.
 *
 * @param {string} content - generated Dafny source
 * @param {string} outputDir - directory to write to
 * @returns {Promise<string>} path to written file
 */
export async function writeObligations(content, outputDir) {
  const outPath = join(outputDir, 'obligations.dfy');
  await writeFile(outPath, content);
  return outPath;
}
